;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	avy-goto-char-2
	backward-sexp
	c-electric-colon
	c-electric-delete-forward
	c-electric-paren
	c-electric-semi&comma
	c-electric-slash
	c-electric-star
	c-indent-line-or-region
	comment-dwim
	company-complete
	dabbrev-expand
	delete-horizontal-space
	electric-newline-and-maybe-indent
	forward-sexp
	haskell-indentation-common-electric-command
	indent-for-tab-command
	kill-region
	mark-sexp
	markdown-enter-key
	markdown-outdent-or-delete
	paredit-backward-kill-word
	paredit-forward-delete
	rjsx-delete-creates-full-tag
	rjsx-electric-gt
	rjsx-electric-lt
	sgml-slash
	toggle-comment-region
	transpose-words
	yaml-electric-backspace
	))

(setq mc/cmds-to-run-once
      '(
	end-of-buffer
	python-shell-send-buffer
	scroll-down-line
	scroll-up-line
	shrink-window
	switch-window
	))
